version: '3'

services:

  postgres:
   restart: always
   image: postgres:latest
   volumes:
    - data:/var/lib/postgresql/data
   ports:
    - "5432"
   environment:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_DB: db

  server:
   restart: always
   image: terminaljack/app_server
   ports:
    - "8080:8080"
  
  order:
   restart: always
   image: terminaljack/app_order
   ports:
    - "5000:5000"
   depends_on:
    - postgres
    - server

volumes:
  data:
