version: '3'

services:
    
  nginx: 
   restart: always
   image: nginx:latest
   container_name: production_nginx
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
     - '80:80'
     - '443:443'
    
  certbot:
    image: certbot/certbot
    
volumes:
  data:
