version: '3'

services:

  postgres:
   restart: always
   image: postgres:latest
   volumes:
    - data:/var/lib/postgresql/data
   ports:
    - "5432"
   environment:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_DB: db

  server:
   restart: always
   image: terminaljack/app_server:service
   ports:
    - "8080:8080"
  
  order:
   restart: always
   image: terminaljack/app_order:app
   depends_on:
    - postgres
    - server
    
  nginx: 
   image: nginx:latest
   container_name: production_nginx
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
     - 80:80
   depends_on:
    - order

volumes:
  data:
